name: "Combine Dependabot pull requests"
on:
  schedule:
    - cron: "0 20 * * 1"
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "no-combine"
          baseBranch: "gh-pages"
          openPR: true
