on:
  issue_comment:
    types: [created]

jobs:
  update_library:
    runs-on: macOS-latest
    name: Update library
    if: ${{ github.event.issue.number == 430 }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update library
        uses: katydecorah/font-library-action@0.1.0
        env:
          GoogleToken: ${{ secrets.GoogleToken }}
      - name: Commit files
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated font library"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
